### ISSUE TITLE
Nice.

### ISSUE THREAD

**Issue by PepsiYT** [vantr-o/Blooket#2]
Seems like you just plagiarized the code from the other repository, slapped your own Twitter on it and then obfuscated it, then claimed that yours are better. Idk seems fishy to me.

**Comment by vantr-o** [comment]
I made this all lmfao, I have the source code on my computer I have everything. It's obfuscated because Blooket won't let you inject normal code in the console, my Twitter is there to prevent people from stealing the hacks.

**Comment by vantr-o** [comment]
If youre talking about [therealgliz](https://github.com/therealgliz) the hacks don't work and the person running it is fake lol.

**Comment by PepsiYT** [comment]
oh ok, thanks for clearing things up. I'm thinking of making a youtube video on how to reverse engineer (i mean it's javascript website its barely reverse engineering) blooket to make hacks and stuff.

seems like everything is located in the `stateNode` object

**Comment by PepsiYT** [comment]
> If youre talking about [therealgliz](https://github.com/therealgliz) the hacks don't work and the person running it is fake lol.

oh yeah one last thing, i liked that because it wasnt obfuscated, can i have the source for this?

**Comment by vantr-o** [comment]
The reason i dont give out source is so I don't have people stealing my hack and removing the credit, the code won't work unobfusucated so probably not.

**Comment by PepsiYT** [comment]
well I see in your description you mention somethin about the new API, i'm trying to make my own hack utility so could you atleast tell me how that works or smth? thats why id want the source

**Comment by intertransfer** [comment]
> If youre talking about [therealgliz](https://github.com/therealgliz) the hacks don't work and the person running it is fake lol.

whats even funnier is that that's actually gliz, and you skidded it all from him. wonder why your own hacks dont work then?

**Comment by Jude-Gideon** [comment]
lol, the footer is the same the rest is all my work, if i stole all of the real gliz hacks my hacks wouldnt work yet they do.

**Comment by Jude-Gideon** [comment]
> > lol, the footer is the same the rest is all my work, if i stole all of the real gliz hacks my hacks wouldnt work yet they do.
> 
> 
> 
> the rest isn't all your work, mainly what's there are pointless obfuscator methods the deobfuscator couldn't remove.
> 
> and many people are saying your hacks dont work, whats up with that?
> 
> they also share the same naming scheme.

Maybe because I use the same obfucsator? Are you stupid

**Comment by Jude-Gideon** [comment]
Also I haven't heard anyone say my codes broke..

**Comment by intertransfer** [comment]
> > > lol, the footer is the same the rest is all my work, if i stole all of the real gliz hacks my hacks wouldnt work yet they do.
> > 
> > 
> > the rest isn't all your work, mainly what's there are pointless obfuscator methods the deobfuscator couldn't remove.
> > and many people are saying your hacks dont work, whats up with that?
> > they also share the same naming scheme.
> 
> Maybe because I use the same obfucsator? Are you stupid

Are you? Gliz doesn't even obfuscate anything. And the other methods "code" are just dead code added by the obfuscator.

https://github.com/Jude-Gideon/Blooket/issues/75

**Comment by Jude-Gideon** [comment]
He used to can you get off my dick lmao I make my own hacks

**Comment by Jude-Gideon** [comment]
> > > > lol, the footer is the same the rest is all my work, if i stole all of the real gliz hacks my hacks wouldnt work yet they do.
> > > 
> > > 
> > > the rest isn't all your work, mainly what's there are pointless obfuscator methods the deobfuscator couldn't remove.
> > > and many people are saying your hacks dont work, whats up with that?
> > > they also share the same naming scheme.
> > 
> > 
> > Maybe because I use the same obfucsator? Are you stupid
> 
> Are you? Gliz doesn't even obfuscate anything. And the other methods "code" are just dead code added by the obfuscator.
> 
> #75

That account is brand new and also is stealing my code 💀
